name: Deploy to production
on:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    steps:

      # Étape 1 : Cloner le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer SSH pour le serveur
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts  

      # Étape 3 : Obtenir la date
      - name: Get current date and set app name
        run: |
          echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "myapp=compta" >> $GITHUB_ENV
          echo "environnement=production" >> $GITHUB_ENV

      # Étape 4 : Configurer QEMU pour la construction multiplateforme
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Étape 5 : Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 6 : Se connecter à GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Étape 7 : Récupérer le nom du repo en minuscule
      - name: Extract repository name in lowercase
        id: repo_name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Étape 8 : Construire et pousser l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./
          file: ./${{ env.environnement }}/Dockerfile
          tags: |
            ghcr.io/${{ env.REPO_NAME }}-${{ env.environnement }}:${{ github.sha }}
            ghcr.io/${{ env.REPO_NAME }}-${{ env.environnement }}:latest
          build-args: |
            CACHEBUST=${{ github.sha }}  # Cache-busting
            NEXT_PUBLIC_PLASMIC_PROJECT_ID=${{ secrets.NEXT_PUBLIC_PLASMIC_PROJECT_ID }}
            NEXT_PUBLIC_PLASMIC_PROJECT_TOKEN=${{ secrets.NEXT_PUBLIC_PLASMIC_PROJECT_TOKEN }}
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
            NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=${{ secrets.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN }}

      # Étape 9 : Authentifier Docker sur le serveur
      - name: Authenticate Docker on the server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} "
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          "
        
      # Étape 10 : Déployer la version de production sur le vps
      - name: Deploy production on vps
        run: |
          ssh  -o StrictHostKeyChecking=no -T ubuntu@${{ secrets.SERVER_IP }} "
            cd ${{ env.myapp }}/${{ env.environnement }} &&
            docker compose -f docker-compose.yml pull &&
            docker compose -f docker-compose.yml up -d
          "

      # Étape 11 : Nettoyer Docker sur le serveur
      - name: Clean up Docker on Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} "
            echo 'Starting Docker cleanup...' &&
            echo 'Before cleanup:' &&
            df -h &&
            docker system prune -a --force &&
            docker image prune -a --force &&
            docker volume prune --force &&
            docker network prune --force &&
            echo 'After cleanup:' &&
            df -h &&
            echo 'Docker cleanup completed successfully.'
          "

    concurrency:
      group: docker-build-${{ github.ref }}
      cancel-in-progress: true