name: Test & Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    steps:

      # Étape 1 : Cloner le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Configurer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Étape 3 : Installer les dépendances
      - name: Install dependencies
        run: |
          cd tests
          npm ci

      # Étape 4 : Création du cache npm
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Étape 5 : Création du cache des navigateurs de playwright
      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-
      
              
      # Étape 6 : Créer une archive des dépendances NPM
      - name: Create archive of node_modules
        run: |
          tar -czf node_modules.tar.gz ./tests/node_modules

      # Étape 7 : Sauvegarder l'archive comme artifact
      - name: Upload node_modules as artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-modules
          path: node_modules.tar.gz

  jest-tests:
    name: Jest Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:

      # Étape 8 : Cloner le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 9 : Restaurer les node_modules
      - name: Restore node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules
      
      # Étape 10 : Extraire l'archive
      - name: Extract node_modules
        run: |
          tar -xzf node_modules.tar.gz

      # Étape 11 : Exécuter les tests Jest
      - name: Run Jest tests
        run: |
          cd tests
          npm install
          npm test

      # Étape 12 : Générer le rapport Jest
      - name: Generate Jest Report
        run: |
          cd tests
          npm test -- --coverage --outputFile=jest-report.json

      # Étape 13 : Télécharger le rapport Jest
      - name: Upload Jest Report
        uses: actions/upload-artifact@v4
        with:
          name: jest-report
          path: test/jest-report.json

  playwright-tests:
    name: Playwright Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:

      # Étape 14 : Cloner le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 15 : Restaurer les node_modules
      - name: Restore node_modules
        uses: actions/download-artifact@v4
        with:
          name: node-modules

      # Étape 16 : Extraire l'archive
      - name: Extract node_modules
        run: |
          tar -xzf node_modules.tar.gz

      # Étape 17 : Installer les dépendances
      - name: Install dependencies
        run: |
          cd tests
          npm ci  # Installation propre des dépendances

      # Étape 18 : Installer les dépendances AVANT Playwright
      - name: Install dependencies
        run: |
          cd tests
          npm install

      # Étape 19 : Installer Playwright et ses navigateurs
      - name: Install Playwright and Browsers
        run: |
          cd tests
          npx playwright install


      # Étape 20 : Exécuter les tests Playwright
      - name: Run Playwright tests
        run: |
          cd tests
          npx playwright test

      # Étape 21 : Générer le rapport Playwright
      - name: Generate Playwright Report
        run: |
          cd tests
          npx playwright test --reporter=json

      # Étape 22 : Télécharger le rapport Playwright
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: tests/playwright-report.json

  deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    needs: [jest-tests, playwright-tests]
    steps:

      # Étape 23 : Cloner le code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 23 : Configurer SSH pour le serveur
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts  

      # Étape 24 : Obtenir la date
      - name: Get current date and set app name
        run: |
          echo "date=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "myapp=jam" >> $GITHUB_ENV
          echo "environnement=staging" >> $GITHUB_ENV

      # Étape 25 : Configurer QEMU pour la construction multiplateforme
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      # Étape 26 : Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 27 : Se connecter à GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      # Étape 28 : Récupérer le nom du repo en minuscule
      - name: Extract repository name in lowercase
        id: repo_name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # Étape 29 : Construire et pousser l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./
          file: ./${{ env.environnement }}/Dockerfile
          tags: |
            ghcr.io/${{ env.REPO_NAME }}-${{ env.environnement }}:${{ github.sha }}
            ghcr.io/${{ env.REPO_NAME }}-${{ env.environnement }}:latest
          build-args: |
            CACHEBUST=${{ github.sha }}  # Cache-busting
            NEXT_PUBLIC_PLASMIC_PROJECT_ID=${{ secrets.NEXT_PUBLIC_PLASMIC_PROJECT_ID }}
            NEXT_PUBLIC_PLASMIC_PROJECT_TOKEN=${{ secrets.NEXT_PUBLIC_PLASMIC_PROJECT_TOKEN }}
            NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
            NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
            NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN=${{ secrets.NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN }}

      # Étape 30 : Authentifier Docker sur le serveur
      - name: Authenticate Docker on the server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} "
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
      # Étape 31 : Déployer la version de staging sur le vps
      - name: Deploy Staging on vps
        run: |
          ssh  -o StrictHostKeyChecking=no -T ubuntu@${{ secrets.SERVER_IP }} "
            cd ${{ env.myapp }}/${{ env.environnement }} &&
            docker compose -f docker-compose.yml pull &&
            docker compose -f docker-compose.yml up -d
          "

      # Étape 32 : Nettoyer le serveur Docker
      - name: Clean up Docker on staging Server
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.SERVER_IP }} "
            echo 'Starting Docker cleanup...' &&
            echo 'Before cleanup:' &&
            df -h &&
            docker system prune -a --force &&
            docker image prune -a --force &&
            docker volume prune --force &&
            docker network prune --force &&
            echo 'After cleanup:' &&
            df -h &&
            echo 'Docker cleanup completed successfully.'
          "

    concurrency:
      group: docker-build-${{ github.ref }}
      cancel-in-progress: true